version: '3'

services:
    web:
        restart: always
        build: .
        expose:
            - "8000"
        links:
            - db:db
        volumes:
            - .:/code
        env_file: .env
        command: /usr/local/bin/gunicorn fourfridays.wsgi:application -w 2 -b :8000
        depends_on:
            - db

    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "80:80"
        volumes:
            - ./static:/code/static
            - ./media:/code/media
        links:
            - web:web

    db:
        restart: always
        image: postgres:latest
        expose:
            - "5432"
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata: