# Generated by Django 2.2.5 on 2019-10-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='40 character limit.', max_length=140, null=True),
        ),
    ]
