# Generated by Django 4.0.2 on 2022-03-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
