# Generated by Django 5.1.8 on 2025-05-17 18:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_formpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
