name: MASTER

on:
  push:
    branches:
      - 'master'
    release:
      types: [published, edited]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64, fourfridays-runner]
    # runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: 'Log in to the Container registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: 'Build and push'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |-
              linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: 'Deploy to K8s Deployment'
        run: |
          kubectl -n fourfridays apply -f ./kube/prod/

      - name: 'Restart Kubernetes Deployment'
        run: |
          kubectl -n fourfridays rollout restart deployment fourfridays